version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: feedback_db
    environment:
      POSTGRES_DB: feedback_system_db
      POSTGRES_USER: feedback_user
      POSTGRES_PASSWORD: feedback_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feedback_user -d feedback_system_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: feedback_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/feedback_system_db
      SPRING_DATASOURCE_USERNAME: feedback_user
      SPRING_DATASOURCE_PASSWORD: feedback_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
